name = "plate-dashboard"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "plate-db-staging"
database_id = "f78b4874-2b55-4092-ba6f-1c6b27e64f48"
