name = "plate-dashboard"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "plate-db-v2"
database_id = "95b57144-a46f-4703-bd73-be5081d66829"
